# Generated by Django 5.0.6 on 2024-07-06 04:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_producto_id_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('impuesto', models.BigIntegerField(default=0)),
                ('estado', models.IntegerField(default=3)),
                ('valor_envio', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='web.pedido')),
            ],
        ),
    ]
