# Generated by Django 5.0.6 on 2024-07-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_producto_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_producto',
            new_name='id',
        ),
    ]
